pdf:
	pdflatex GraphBLAS_API_C.tex
	pdflatex GraphBLAS_API_C.tex
	pdflatex GraphBLAS_API_C.tex

sym:
	pdflatex symb.tex
	pdflatex symb.tex
	pdflatex symb.tex

clean:
	rm -f GraphBLAS_API_C.aux GraphBLAS_API_C.log GraphBLAS_API_C.out GraphBLAS_API_C.toc symb.aux symb.log symb.out symb.toc

cleanall: clean
	rm -f GraphBLAS_API_C.pdf
